import littleLife from './assets/a-little-life.webp'
import us from './assets/us.webp'
import surroundedByIdiots from './assets/surrounded-by-idiots.webp'
import tsou from './assets/tsou.webp'
import cainsJawbone from './assets/cains-jawbone.webp'
import pluto from './assets/pluto.webp'
import alone from './assets/art-of-being-alone.webp'
import blank from './assets/blank.webp'
import sheComesFirst from './assets/she-comes-first.webp'
import greatGatsby from './assets/great-gatsby.webp'

export const cartItems = [{
    title: "Cain's Jawbone",
    author: "E. Powys Mathers",
    genres: ["Mystery", "Thriller", "Classics", "Crime", "Fiction"],
    price: 10.99,
    description: "Six murders. One hundred pages. Millions of possible combinations... but only one is correct. Can you solve Torquemada's murder mystery? ",
    coverImage: cainsJawbone,
    publicationDate: new Date("1934-01-01"),
    isbn: "4780743278",
    language: "English",
    pages: 100,
    stock: 12,
    rating: 4.5,
    reviews: [
      {
        userId: "607f1f77bcf86cd799439011",
        reviewText: "A fascinating glimpse into the 1920s.",
        rating: 5,
        createdAt: "1 week ago",
      },
      {
        userId: "607f1f77bcf86cd799439012",
        reviewText: "Interesting characters, but the pacing felt slow.",
        rating: 3,
        createdAt: "1 week ago",
      },
    ],
  },{
    title: "Pluto",
    author: "Chao Pla Noy (เจ้าปลาน้อย)",
    genres: ["Girl Love / Yuri"],
    price: 10.99,
    description: "There's no reason when it comes to love. If there were, it wouldn't be love. What should I do? Metavee loves me, but she understands that I am her twin. If this love is revealed, the two of us will have to end, and I will be just a dwarf planet in the solar system. It existed once but slipped away into oblivion. And being forgotten is equivalent to... Never existed.",
    coverImage: pluto,
    publicationDate: new Date("1925-04-10"),
    isbn: "5780735605",
    language: "English",
    pages: 180,
    stock: 12,
    rating: 4.5,
    reviews: [
      {
        userId: "607f1f77bcf86cd799439011",
        reviewText: "A fascinating glimpse into the 1920s.",
        rating: 5,
        createdAt: "1 week ago",
      },
      {
        userId: "607f1f77bcf86cd799439012",
        reviewText: "Interesting characters, but the pacing felt slow.",
        rating: 3,
        createdAt: "1 week ago",
      },
    ],
  },{
    title: "Blank",
    author: "Chao Pla Noy (เจ้าปลาน้อย)",
    genres: ["Girl Love / Yuri"],
    price: 10.99,
    description: "M.L. Sippakorn, known as 'Miss Nueng,' has lived away from the palace and feels she still has much to learn about life and love. Her world changes when she meets A-Nueng, an 18-year-old girl with captivating eyes who frequently confesses her love for Miss Nueng. Though Miss Nueng is initially annoyed by A-Nueng's persistence, she finds herself drawn to her in a way she never expected. As their bond deepens, Miss Nueng learns that A-Nueng is the daughter of her high school best friend, who disappeared after becoming pregnant. Despite their significant age gap—Miss Nueng being 36 when A-Nueng turns 20—A-Nueng remains undeterred, arguing that love transcends age. With determination, she vows to prove herself worthy of Miss Nueng's affection, filling the emptiness in her life with hope and possibility.",
    coverImage: blank,
    publicationDate: new Date("1925-04-10"),
    isbn: "6772735645",
    language: "English",
    pages: 180,
    stock: 12,
    rating: 4.5,
    reviews: [
      {
        userId: "607f1f77bcf86cd799439011",
        reviewText: "A fascinating glimpse into the 1920s.",
        rating: 5,
        createdAt: "1 week ago",
      },
      {
        userId: "607f1f77bcf86cd799439012",
        reviewText: "Interesting characters, but the pacing felt slow.",
        rating: 3,
        createdAt: "1 week ago",
      },
    ],
}]

export const books = [{
    title: "A Little Life",
    author: "Hanya Yanagihara",
    genres: ["Fiction", "Contemporary", "LGBT", "Literary", "Mental Health"],
    price: 10.99,
    description: "When four classmates from a small Massachusetts college move to New York to make their way, they're broke, adrift, and buoyed only by their friendship and ambition. There is kind, handsome Willem, an aspiring actor; JB, a quick-witted, sometimes cruel Brooklyn-born painter seeking entry to the art world; Malcolm, a frustrated architect at a prominent firm; and withdrawn, brilliant, enigmatic Jude, who serves as their center of gravity.Over the decades, their relationships deepen and darken, tinged by addiction, success, and pride. Yet their greatest challenge, each comes to realize, is Jude himself, by midlife a terrifyingly talented litigator yet an increasingly broken man, his mind and body scarred by an unspeakable childhood, and haunted by what he fears is a degree of trauma that he’ll not only be unable to overcome—but that will define his life forever.",
    coverImage: littleLife,
    publicationDate: new Date("1925-04-10"),
    isbn: "0385539258",
    language: "English",
    pages: 720,
    stock: 12,
    rating: 3.5,
    viewCount: 235,
    reviews: [
      {
        userId: "607f1f77bcf86cd799439011",
        reviewText: "A fascinating glimpse into the 1920s.",
        rating: 5,
        createdAt: "2 days ago",
      },
      {
        userId: "607f1f77bcf86cd799439012",
        reviewText: "Interesting characters, but the pacing felt slow.",
        rating: 3,
        createdAt: "1 week ago",
      },
    ],
  },{
    title: "Us (รักของเรา)",
    author: "Chao Pla Noy (เจ้าปลาน้อย)",
    genres: ["Girl Love / Yuri"],
    price: 10.99,
    description: "I, Dokruk, a simple girl, never thought about loving with a woman but with Pam, a deep-brown eyed dentist, who took my heart with everything of her that I did not know how and why. I felt enchanted with her unique Vanilla perfume every time she appeared. Was it love? However, Pam had a boyfriend, who was my brother. I should not express my feeling with her. How could I do?",
    coverImage: us,
    publicationDate: new Date("2024-01-09"),
    isbn: "1385536789",
    language: "English",
    pages: 180,
    stock: 12,
    rating: 5,
    viewCount: 635,
    reviews: [
      {
        userId: "607f1f77bcf86cd799439011",
        reviewText: "A fascinating glimpse into the 1920s.",
        rating: 5,
        createdAt: "1 week ago",
      },
      {
        userId: "607f1f77bcf86cd799439012",
        reviewText: "Interesting characters, but the pacing felt slow.",
        rating: 3,
        createdAt: "1 week ago",
      },
    ],
  },{
    title: "The Secret of Us",
    author: "มีนาม",
    genres: ["Girl Love / Yuri"],
    price: 10.99,
    description: "A GL novel that often explores themes of love, identity, and personal growth. It typically revolves around the evolving relationship between two female protagonists as they navigate their feelings, societal expectations, and personal challenges. The story usually emphasizes emotional connections, character development, and the journey toward self-acceptance.",
    coverImage: tsou,
    publicationDate: new Date("2024-06-05"),
    isbn: "2679536789",
    language: "English",
    pages: 180,
    stock: 12,
    rating: 4.5,
    viewCount: 285,
    reviews: [
      {
        userId: "607f1f77bcf86cd799439011",
        reviewText: "A fascinating glimpse into the 1920s.",
        rating: 5,
        createdAt: "1 week ago",
      },
      {
        userId: "607f1f77bcf86cd799439012",
        reviewText: "Interesting characters, but the pacing felt slow.",
        rating: 3,
        createdAt: "1 week ago",
      },
    ],
  },{
    title: "Surrounded by Idiots",
    author: "Thomas Erikson",
    genres: ["Nonfiction", "Self Help", "Psychology"],
    price: 10.99,
    description: "A runaway bestseller in Sweden that has sold more than a million copies worldwide, Surrounded by Idiots shares a groundbreaking new method of understanding the people around you that will change how you interact with everyone from your coworkers to your spouse.",
    coverImage: surroundedByIdiots,
    publicationDate: new Date("1925-04-10"),
    isbn: "3780743278",
    language: "English",
    pages: 304,
    stock: 12,
    rating: 4,
    viewCount: 905,
    reviews: [
      {
        userId: "607f1f77bcf86cd799439011",
        reviewText: "A fascinating glimpse into the 1920s.",
        rating: 5,
        createdAt: "1 week ago",
      },
      {
        userId: "607f1f77bcf86cd799439012",
        reviewText: "Interesting characters, but the pacing felt slow.",
        rating: 3,
        createdAt: "1 week ago",
      },
    ],
  },{
    title: "Cain's Jawbone",
    author: "E. Powys Mathers",
    genres: ["Mystery", "Thriller", "Classics", "Crime", "Fiction"],
    price: 10.99,
    description: "Six murders. One hundred pages. Millions of possible combinations... but only one is correct. Can you solve Torquemada's murder mystery? ",
    coverImage: cainsJawbone,
    publicationDate: new Date("1934-01-01"),
    isbn: "4780743278",
    language: "English",
    pages: 100,
    stock: 12,
    rating: 4.5,
    viewCount: 205,
    reviews: [
      {
        userId: "607f1f77bcf86cd799439011",
        reviewText: "A fascinating glimpse into the 1920s.",
        rating: 5,
        createdAt: "1 week ago",
      },
      {
        userId: "607f1f77bcf86cd799439012",
        reviewText: "Interesting characters, but the pacing felt slow.",
        rating: 3,
        createdAt: "1 week ago",
      },
    ],
  },{
    title: "Pluto",
    author: "Chao Pla Noy (เจ้าปลาน้อย)",
    genres: ["Girl Love / Yuri"],
    price: 10.99,
    description: "There's no reason when it comes to love. If there were, it wouldn't be love. What should I do? Metavee loves me, but she understands that I am her twin. If this love is revealed, the two of us will have to end, and I will be just a dwarf planet in the solar system. It existed once but slipped away into oblivion. And being forgotten is equivalent to... Never existed.",
    coverImage: pluto,
    publicationDate: new Date("1925-04-10"),
    isbn: "5780735605",
    language: "English",
    pages: 180,
    stock: 12,
    rating: 4,
    viewCount: 23,
    reviews: [
      {
        userId: "607f1f77bcf86cd799439011",
        reviewText: "A fascinating glimpse into the 1920s.",
        rating: 5,
        createdAt: "1 week ago",
      },
      {
        userId: "607f1f77bcf86cd799439012",
        reviewText: "Interesting characters, but the pacing felt slow.",
        rating: 3,
        createdAt: "1 week ago",
      },
    ],
  },{
    title: "Blank",
    author: "Chao Pla Noy (เจ้าปลาน้อย)",
    genres: ["Girl Love / Yuri"],
    price: 10.99,
    description: "M.L. Sippakorn, known as 'Miss Nueng,' has lived away from the palace and feels she still has much to learn about life and love. Her world changes when she meets A-Nueng, an 18-year-old girl with captivating eyes who frequently confesses her love for Miss Nueng. Though Miss Nueng is initially annoyed by A-Nueng's persistence, she finds herself drawn to her in a way she never expected. As their bond deepens, Miss Nueng learns that A-Nueng is the daughter of her high school best friend, who disappeared after becoming pregnant. Despite their significant age gap—Miss Nueng being 36 when A-Nueng turns 20—A-Nueng remains undeterred, arguing that love transcends age. With determination, she vows to prove herself worthy of Miss Nueng's affection, filling the emptiness in her life with hope and possibility.",
    coverImage: blank,
    publicationDate: new Date("1925-04-10"),
    isbn: "6772735645",
    language: "English",
    pages: 180,
    stock: 12,
    rating: 4.75,
    viewCount: 210,
    reviews: [
      {
        userId: "607f1f77bcf86cd799439011",
        reviewText: "A fascinating glimpse into the 1920s.",
        rating: 5,
        createdAt: "1 week ago",
      },
      {
        userId: "607f1f77bcf86cd799439012",
        reviewText: "Interesting characters, but the pacing felt slow.",
        rating: 3,
        createdAt: "1 week ago",
      },
    ],
  },{
    title: "The Art of Being Alone",
    author: "Renuka Gavrani",
    genres: ["Nonfiction", "Self Help", "Psychology"],
    price: 10.99,
    description: "Taylor Swift once said, “The scary news is, you are on your own now. But the cool news is, you are on your own now.” From a young age, we’ve been conditioned to fear loneliness, often seeing the solitary child in stories as weak or in need of rescue. This fear pushes us to conform to an ideal that seeks acceptance, leading to the loss of our true selves. In *The Art of Being Alone*, I share my journey of embracing solitude. While I once longed for companionship to fill the void, I’ve learned to cherish my alone time as an opportunity for growth and self-discovery. This book is not just about loneliness; it’s about transforming that loneliness into empowering solitude and using it to pursue my dreams. Divided into two sections, the first focuses on shifting your mindset from loneliness to solitude, while the second guides you in leveraging that solitude for personal growth. If you’re ready to redefine your relationship with being alone and to work towards a life you love, then welcome to *The Art of Being Alone*. It's time to reclaim your narrative and build the life you've always desired.",
    coverImage: alone,
    publicationDate: new Date("2023-05-17"),
    isbn: "7395000347",
    language: "English",
    pages: 149,
    stock: 12,
    rating: 3,
    viewCount: 678,
    reviews: [
      {
        userId: "607f1f77bcf86cd799439011",
        reviewText: "A fascinating glimpse into the 1920s.",
        rating: 5,
        createdAt: "1 week ago",
      },
      {
        userId: "607f1f77bcf86cd799439012",
        reviewText: "Interesting characters, but the pacing felt slow.",
        rating: 3,
        createdAt: "1 week ago",
      },
    ],
  },{
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    genres: ["Classic", "Fiction"],
    price: 10.99,
    description: "*The Great Gatsby* follows Nick Carraway, who moves to West Egg and becomes drawn into the world of his wealthy neighbor, Jay Gatsby. Gatsby is obsessed with reuniting with his former love, Daisy Buchanan, who is now married to the affluent Tom Buchanan. The novel explores themes of wealth, class, and the American Dream as Gatsby's pursuit of Daisy leads to tragedy. Ultimately, it highlights the disillusionment behind the glamorous facade of 1920s America, culminating in Gatsby's downfall and Nick's return to the Midwest.",
    coverImage: greatGatsby,
    publicationDate: new Date("1925-04-10"),
    isbn: "8786835635",
    language: "English",
    pages: 180,
    stock: 12,
    rating: 4.5,
    viewCount: 78,
    reviews: [
      {
        userId: "607f1f77bcf86cd799439011",
        reviewText: "A fascinating glimpse into the 1920s.",
        rating: 5,
        createdAt: "1 week ago",
      },
      {
        userId: "607f1f77bcf86cd799439012",
        reviewText: "Interesting characters, but the pacing felt slow.",
        rating: 3,
        createdAt: "1 week ago",
      },
    ],
  },{
    title: "She Comes First",
    author: "Ian Kerner",
    genres: ["Nonfiction", "Self Help", "Health", "Sexuality"],
    price: 10.99,
    description: "Ian Kerner offers a radical new philosophy for pleasuring women in She Comes First—an essential guidebook to oral sex from the author of Be Honest—You’re Not That Into Him Either. The New York Times praises Kerner’s “cool sense of humor and an obsessive desire to inform,” as he “encourages men through an act that many find mystifying.” An indispensable aid to a healthier, more fulfilling sex life for her and him, She Comes First offers techniques and philosophy that have already earned raves from the likes of bestselling author and Loveline co-host Dr. Drew Pinsky as well as Playgirl magazine, which cheers, “Hallelujah!”.",
    coverImage: sheComesFirst,
    publicationDate: new Date("2004-01-01"),
    isbn: "9780743273",
    language: "English",
    pages: 228,
    stock: 12,
    rating: 4.5,
    viewCount: 235,
    reviews: [
      {
        userId: "607f1f77bcf86cd799439011",
        reviewText: "A fascinating glimpse into the 1920s.",
        rating: 5,
        createdAt: "1 week ago",
      },
      {
        userId: "607f1f77bcf86cd799439012",
        reviewText: "Interesting characters, but the pacing felt slow.",
        rating: 3,
        createdAt: "1 week ago",
      },
    ],
  },
]